// Event
export const FETCH_EVENT_REQUEST = 'FETCH_EVENT_REQUEST'
export const FETCH_EVENT_SUCCESS = 'FETCH_EVENT_SUCCESS'
export const FETCH_EVENT_ERROR = 'FETCH_EVENT_ERROR'
export const FETCH_EVENT_CREATE_SUCCESS = 'FETCH_EVENT_CREATE_SUCCESS'
export const FETCH_EVENT_UPDATE_SUCCESS = 'FETCH_EVENT_UPDATE_SUCCESS'
export const EVENT_UPDATE = 'EVENT_UPDATE'

export const EVENT_EDITOR_CHANGE = 'EVENT_EDITOR_CHANGE'
export const RESET_EVENT_EDITOR = 'RESET_EVENT_EDITOR'

// Events
export const FETCH_EVENTS_REQUEST = 'FETCH_EVENTS_REQUEST'
export const FETCH_EVENTS_SUCCESS = 'FETCH_EVENTS_SUCCESS'
export const FETCH_EVENTS_ERROR = 'FETCH_EVENTS_ERROR'
export const UPDATE_EVENTS = 'UPDATE_EVENTS'

export const HANDLE_CHANGE_TABLE = 'HANDLE_CHANGE_TABLE'

export const OPEN_SNACKBAR = 'OPEN_SNACKBAR'
export const CLOSE_SNACKBAR = 'CLOSE_SNACKBAR'

// Users
export const FETCH_USER_REQUEST = 'FETCH_USER_REQUEST'
export const FETCH_USER_SUCCESS = 'FETCH_USER_SUCCESS'
export const FETCH_USER_ERROR = 'FETCH_USER_ERROR'

// Tickets
export const FETCH_TICKETS_SUCCESS = 'FETCH_TICKETS_SUCCESS'
export const FETCH_TICKET_SUCCESS = 'FETCH_TICKET_SUCCESS'
export const FETCH_CREATE_TICKET_SUCCESS = 'FETCH_CREATE_TICKET_SUCCESS'
export const HANDLE_UPDATE_TICKET = 'HANDLE_UPDATE_TICKET'
