export const RESET_EVENT = 'RESET_EVENT'
export const VIEW_EVENT = 'VIEW_EVENT'
export const HANDLE_EVENT_CHANGE = 'HANDLE_EVENT_CHANGE'
export const HANDLE_TICKET_CHANGE = 'HANDLE_TICKET_CHANGE'

// FETCH
export const FETCH_USER_SUCCESS = 'FETCH_USER_SUCCESS'
export const FETCH_USER_FAILURE = 'FETCH_USER_FAILURE'
export const FETCH_EVENT_SUCCESS = 'FETCH_EVENT_SUCCESS'
export const FETCH_EVENTS_SUCCESS = 'FETCH_EVENTS_SUCCESS'
export const FETCH_TICKET_PRICE_SUCCESS = 'FETCH_TICKET_PRICE_SUCCESS'
