export const eventColumnData = [
  { label: 'Name', attribute: 'title' },
  { label: 'Location', attribute: 'venue_name' },
  { label: 'Capacity', attribute: 'venue_capacity' },
  { label: 'Status', attribute: 'status' },
  { label: 'Date', attribute: 'start_date' },
  // { label: 'Description', attribute: 'description' },
  // { label: 'Disclaimer', attribute: 'disclaimer' },
  // { label: 'End Date', attribute: 'end_date' },
  // { label: 'End Time', attribute: 'end_time' },
  // { label: 'External URL', attribute: 'external_url' },
  // { label: 'Slug', attribute: 'slug ' },
  // { label: 'Start Time', attribute: 'start_time' },
  // { label: 'Summary', attribute: 'summary' },
  // { label: 'Time Zone', attribute: 'time_zone' },
  // { label: 'Type', attribute: 'type' },
  // { label: 'Street', attribute: 'venue_street' },
]
