export default {
  display5: 'h1',
  display4: 'h1',
  display3: 'h1',
  display2: 'h1',
  display1: 'h1',
  headline: 'h1',
  title: 'h2',
  subheading: 'h3',
  body3: 'p',
  body2: 'aside',
  body1: 'p',
  caption: 'span',
  label: 'label',
  button1: 'button',
  button2: 'button',
  button3: 'button',
}
