// Event
export const FETCH_EVENT_SUCCESS = 'FETCH_EVENT_SUCCESS'
export const FETCH_EVENT_OWNER_SUCCESS = 'FETCH_EVENT_OWNER_SUCCESS'
export const FETCH_EVENT_SCHEDULES_SUCCESS = 'FETCH_EVENT_SCHEDULES_SUCCESS'

// Ticket Price
export const FETCH_TICKET_PRICE_SUCCESS = 'FETCH_TICKET_PRICE_SUCCESS'
export const SELECT_TICKET_PRICE = 'SELECT_TICKET_PRICE'
export const UPDATE_TICKET_WAITLIST = 'UPDATE_TICKET_WAITLIST'
export const REMOVE_TICKET_PRICE = 'REMOVE_TICKET_PRICE'
export const INCREMENT_TICKET = 'INCREMENT_TICKET'
export const FETCH_DATES_SUCCESS = 'FETCH_DATES_SUCCESS'

// Checkout
export const UPDATE_CHECKOUT_ATTRIBUTE = 'UPDATE_CHECKOUT_ATTRIBUTE'
export const FETCH_CREATE_CHECKOUT_SUCCESS = 'FETCH_CREATE_CHECKOUT_SUCCESS'

// Promo Codes
export const APPLY_PROMO_CODE = 'APPLY_PROMO_CODE'
export const PROMO_CODE_ERROR = 'PROMO_CODE_ERROR'
export const PROMO_CODE_SUCCESS = 'PROMO_CODE_SUCCESS'

// Widget
export const UPDATE_WIDGET = 'UPDATE_WIDGET'

// Selected Day
export const SELECT_DAY = 'SELECT_DAY'
