
// Event
export const FETCH_EVENT_SUCCESS = 'FETCH_EVENT_SUCCESS'
export const FETCH_EVENT_OWNER_SUCCESS = 'FETCH_EVENT_OWNER_SUCCESS'

// Ticket Price
export const FETCH_TICKET_PRICE_SUCCESS = 'FETCH_TICKET_PRICE_SUCCESS'
export const SELECT_TICKET_PRICE = 'SELECT_TICKET_PRICE'

// Checkout 
export const UPDATE_CHECKOUT_ATTRIBUTE = 'UPDATE_CHECKOUT_ATTRIBUTE'
export const FETCH_CREATE_CHECKOUT_SUCCESS = 'FETCH_CREATE_CHECKOUT_SUCCESS'
